# Generated by Django 2.2.4 on 2020-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='so bad', max_length=255),
            preserve_default=False,
        ),
    ]
