# Generated by Django 2.2.4 on 2020-12-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_show_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='ShowTV',
        ),
    ]
