# Generated by Django 2.2.4 on 2020-12-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20201215_2050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowTV',
            new_name='ShTV',
        ),
    ]
