# Generated by Django 2.2.4 on 2020-12-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
