# Generated by Django 2.2.4 on 2020-12-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201220_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='like',
        ),
        migrations.AddField(
            model_name='quote',
            name='like',
            field=models.ManyToManyField(related_name='like_set', to='app.Users'),
        ),
    ]
