# Generated by Django 2.2.4 on 2020-12-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojos',
            old_name='city',
            new_name='dojo_city',
        ),
        migrations.RenameField(
            model_name='dojos',
            old_name='name',
            new_name='dojo_name',
        ),
        migrations.RenameField(
            model_name='dojos',
            old_name='state',
            new_name='dojo_state',
        ),
    ]
