# Generated by Django 2.2.4 on 2020-12-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0002_auto_20201214_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojos',
            new_name='dojo',
        ),
    ]
